/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;


import javax.swing.JOptionPane;

import modelo.*;

/**
 *
 * @author Yudys
 */
public class AGREGAR_LIBROS extends javax.swing.JPanel {

    /**
     * Creates new form AGREGAR_USUARIO
     */
    public AGREGAR_LIBROS() {
        initComponents();

    }

    private void limpiar() {
        TxtGenero.setText("");
        TxtAutor.setText("");
        TxtAnio.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtAutor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtGenero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtAnio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BtnLimpiar = new javax.swing.JButton();
        btnAgregarUser = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtTitulo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("AUTOR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 130, 30));

        TxtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAutorActionPerformed(evt);
            }
        });
        jPanel1.add(TxtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 190, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("GENERO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 130, 30));
        jPanel1.add(TxtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("AÑO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 160, 30));
        jPanel1.add(TxtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 190, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("PRESTADO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 130, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("AGREGAR LIBRO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 230, 70));

        BtnLimpiar.setText("LIMPIAR");
        BtnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLimpiarMouseClicked(evt);
            }
        });
        jPanel1.add(BtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 160, 60));

        btnAgregarUser.setText("AGREGAR LIBRO");
        btnAgregarUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarUserMouseClicked(evt);
            }
        });
        btnAgregarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUserActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 160, 60));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRESTADO", "NO PRESTADO" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 170, 40));

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 190, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("TÍTULO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLimpiarMouseClicked
        String[] options = {"Sí quiero usarlo", "No quiero usarlo"};
        int choice = JOptionPane.showOptionDialog(
                null,
                "¿Quiqere borrar el texto en los cuadros de texto?",
                "BORRAR TEXTO EN CUADROPS DE TEXTO",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]
        );

        if (choice == 0) {
            limpiar();
        } else if (choice == 1) {
            return;
        } else {
            System.out.println("El usuario cerró el diálogo sin elegir");
        }

    }//GEN-LAST:event_BtnLimpiarMouseClicked

    private void btnAgregarUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarUserMouseClicked
        String autor = TxtAutor.getText();
        String genero = TxtGenero.getText();
        String titulo = txtTitulo.getText();

        if (autor.isEmpty() || genero.isEmpty() || TxtAnio.getText().isEmpty() || titulo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, llene todos los campos");
            return;
        }

        int anio;
        try {
            anio = Integer.parseInt(TxtAnio.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un año válido");
            return;
        }

        boolean prestado = jComboBox1.getSelectedItem().toString().equals("PRESTADO");
        System.out.println("Prestado status: " + prestado); // Debug line

        libro lib = new libro();
        if (lib.crearLibro(autor, anio, genero, titulo, prestado)) {
            JOptionPane.showMessageDialog(null, "Libro creado con éxito. Prestado: " + prestado);
            limpiar();
            dashboard.cambiarPanel(new libros_actuales());
        } else {
            JOptionPane.showMessageDialog(null, "El libro no pudo ser creado");
        }
        dashboard.cambiarPanel(new libros_actuales());
    }//GEN-LAST:event_btnAgregarUserMouseClicked

    private void btnAgregarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarUserActionPerformed

    private void TxtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAutorActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JTextField TxtAnio;
    private javax.swing.JTextField TxtAutor;
    private javax.swing.JTextField TxtGenero;
    private javax.swing.JButton btnAgregarUser;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
