/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Yudys
 */
public class devoluciones extends javax.swing.JPanel {

    /**
     * Creates new form devolciones
     */
    public devoluciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BGreturn = new javax.swing.JLabel();
        BtnDevolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TxtIDLIBRO = new javax.swing.JTextField();
        TxtIDLIBRO1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BGreturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/devolver__Fondo-removebg-preview.png"))); // NOI18N
        jPanel1.add(BGreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 1050, -1));

        BtnDevolver.setBackground(new java.awt.Color(0, 153, 51));
        BtnDevolver.setText("Devolver");
        jPanel1.add(BtnDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 180, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID LIBRO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 90, 20));

        TxtIDLIBRO.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(TxtIDLIBRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 150, -1));

        TxtIDLIBRO1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(TxtIDLIBRO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 150, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID USUARIO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 110, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGreturn;
    private javax.swing.JButton BtnDevolver;
    private javax.swing.JTextField TxtIDLIBRO;
    private javax.swing.JTextField TxtIDLIBRO1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
