/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Yudys
 */
public class principal_vista extends javax.swing.JPanel {

    /**
     * Creates new form principal_vista
     */
    public principal_vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlBackGround = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LblWelcome2 = new javax.swing.JLabel();
        LblWelcome3 = new javax.swing.JLabel();
        LblWelcome4 = new javax.swing.JLabel();
        LblWelcome5 = new javax.swing.JLabel();
        LblWelcome = new javax.swing.JLabel();
        LblWelcome1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        PnlBackGround.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("disponibles para préstamo y consulta. Explora, descubre y sumérgete en el ");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("mundo del conocimiento que hemos reunido para ti.");

        LblWelcome2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        LblWelcome2.setForeground(new java.awt.Color(0, 0, 0));
        LblWelcome2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblWelcome2.setText("Esta aplicación está diseñada para facilitar la administración y el uso de nuestros recursos bibliográficos.");
        LblWelcome2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        LblWelcome3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        LblWelcome3.setForeground(new java.awt.Color(0, 0, 0));
        LblWelcome3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblWelcome3.setText("Desde aquí, puedes buscar libros, gestionar préstamos, hacer devoluciones y acceder a nuestras recomendaciones de");
        LblWelcome3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        LblWelcome4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        LblWelcome4.setForeground(new java.awt.Color(0, 0, 0));
        LblWelcome4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblWelcome4.setText("lectura. Nos esforzamos por hacer que tu experiencia de usuario sea intuitiva y eficiente, ");
        LblWelcome4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        LblWelcome5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        LblWelcome5.setForeground(new java.awt.Color(0, 0, 0));
        LblWelcome5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblWelcome5.setText("para que encuentres lo que necesitas sin complicaciones.");
        LblWelcome5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        LblWelcome.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        LblWelcome.setForeground(new java.awt.Color(0, 0, 0));
        LblWelcome.setText("Bienvenido");

        LblWelcome1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        LblWelcome1.setForeground(new java.awt.Color(0, 0, 0));
        LblWelcome1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblWelcome1.setText("¡Bienvenido a la Biblioteca LIBNI Aquí encontrarás una amplia colección de libros");
        LblWelcome1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout PnlBackGroundLayout = new javax.swing.GroupLayout(PnlBackGround);
        PnlBackGround.setLayout(PnlBackGroundLayout);
        PnlBackGroundLayout.setHorizontalGroup(
            PnlBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
            .addGroup(PnlBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnlBackGroundLayout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addGroup(PnlBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PnlBackGroundLayout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(LblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(539, 539, 539))
                        .addGroup(PnlBackGroundLayout.createSequentialGroup()
                            .addComponent(LblWelcome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(201, 201, 201))
                        .addGroup(PnlBackGroundLayout.createSequentialGroup()
                            .addGroup(PnlBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PnlBackGroundLayout.createSequentialGroup()
                                    .addComponent(LblWelcome2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(64, 64, 64))
                                .addComponent(LblWelcome3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PnlBackGroundLayout.createSequentialGroup()
                                    .addComponent(LblWelcome4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(154, 154, 154))
                                .addGroup(PnlBackGroundLayout.createSequentialGroup()
                                    .addComponent(LblWelcome5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(320, 320, 320))
                                .addGroup(PnlBackGroundLayout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(155, 155, 155))
                                .addGroup(PnlBackGroundLayout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(302, 302, 302)))
                            .addGap(78, 78, 78)))))
        );
        PnlBackGroundLayout.setVerticalGroup(
            PnlBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
            .addGroup(PnlBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnlBackGroundLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(LblWelcome1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(43, 43, 43)
                    .addComponent(LblWelcome2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(LblWelcome3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(LblWelcome4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(LblWelcome5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(PnlBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblWelcome;
    private javax.swing.JLabel LblWelcome1;
    private javax.swing.JLabel LblWelcome2;
    private javax.swing.JLabel LblWelcome3;
    private javax.swing.JLabel LblWelcome4;
    private javax.swing.JLabel LblWelcome5;
    private javax.swing.JPanel PnlBackGround;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
