/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Yudys
 */
public class reportes_principal extends javax.swing.JPanel {

    /**
     * Creates new form reportes_principal
     */
    public reportes_principal() {
        initComponents();
        cambiarPanel(new reportes());
    }
    public void cambiarPanel(JPanel p)
    {
        p.setSize(810, 370);
        p.setLocation(0, 0);
        panel_contenido.removeAll();
        panel_contenido.add(p, BorderLayout.CENTER);
        panel_contenido.revalidate();
        panel_contenido.repaint();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEntregados = new javax.swing.JButton();
        btnPrestados = new javax.swing.JButton();
        panel_contenido = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("REPORTES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 6, 250, 40));

        btnEntregados.setText("LIBROS ENTREGADOS");
        btnEntregados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntregadosMouseClicked(evt);
            }
        });
        jPanel1.add(btnEntregados, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 170, 60));

        btnPrestados.setText("LIBROS PRESTADOS");
        btnPrestados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrestadosMouseClicked(evt);
            }
        });
        jPanel1.add(btnPrestados, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 170, 60));

        javax.swing.GroupLayout panel_contenidoLayout = new javax.swing.GroupLayout(panel_contenido);
        panel_contenido.setLayout(panel_contenidoLayout);
        panel_contenidoLayout.setHorizontalGroup(
            panel_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        panel_contenidoLayout.setVerticalGroup(
            panel_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jPanel1.add(panel_contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 810, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntregadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntregadosMouseClicked
        cambiarPanel(new REPORTES_ENTREGADOS());
    }//GEN-LAST:event_btnEntregadosMouseClicked

    private void btnPrestadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestadosMouseClicked
        cambiarPanel(new reportes());
    }//GEN-LAST:event_btnPrestadosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntregados;
    private javax.swing.JButton btnPrestados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_contenido;
    // End of variables declaration//GEN-END:variables
}
