package biblioteca;


import java.awt.Color;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {


    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlBackGround = new javax.swing.JPanel();
        PnlLogingBackground = new javax.swing.JPanel();
        LblLogin = new javax.swing.JLabel();
        LblUsuario = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JTextField();
        LblPassword = new javax.swing.JLabel();
        Password_1 = new javax.swing.JPasswordField();
        BtnIngresar = new javax.swing.JButton();
        Separator_user = new javax.swing.JSeparator();
        Separator_password = new javax.swing.JSeparator();
        Lbl_Libros_imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setLocationByPlatform(true);
        setResizable(false);

        PnlBackGround.setBackground(new java.awt.Color(204, 255, 204));

        PnlLogingBackground.setBackground(new java.awt.Color(153, 255, 153));
        PnlLogingBackground.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PnlLogingBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LblLogin.setForeground(new java.awt.Color(0, 0, 0));
        LblLogin.setText("Login");
        PnlLogingBackground.add(LblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 61, 36));

        LblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        LblUsuario.setText("Usuario");
        PnlLogingBackground.add(LblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 59, 30));

        TxtUsuario.setBackground(new java.awt.Color(153, 255, 153));
        TxtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        TxtUsuario.setText("Nombre de usuario aquí");
        TxtUsuario.setBorder(null);
        TxtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtUsuarioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtUsuarioMousePressed(evt);
            }
        });
        TxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioActionPerformed(evt);
            }
        });
        PnlLogingBackground.add(TxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 106, 250, -1));

        LblPassword.setForeground(new java.awt.Color(0, 0, 0));
        LblPassword.setText("Contraseña");
        PnlLogingBackground.add(LblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        Password_1.setBackground(new java.awt.Color(153, 255, 153));
        Password_1.setForeground(new java.awt.Color(204, 204, 204));
        Password_1.setText("clavejaja");
        Password_1.setBorder(null);
        Password_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Password_1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Password_1MousePressed(evt);
            }
        });
        PnlLogingBackground.add(Password_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 250, 20));

        BtnIngresar.setBackground(new java.awt.Color(0, 153, 0));
        BtnIngresar.setText("Ingresar");
        BtnIngresar.setToolTipText("");
        BtnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnIngresarMouseExited(evt);
            }
        });
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });
        PnlLogingBackground.add(BtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 100, 50));

        Separator_user.setForeground(new java.awt.Color(0, 0, 0));
        PnlLogingBackground.add(Separator_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 123, 250, 10));

        Separator_password.setForeground(new java.awt.Color(0, 0, 0));
        PnlLogingBackground.add(Separator_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 250, 20));

        Lbl_Libros_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/biblioteca.jpg"))); // NOI18N

        javax.swing.GroupLayout PnlBackGroundLayout = new javax.swing.GroupLayout(PnlBackGround);
        PnlBackGround.setLayout(PnlBackGroundLayout);
        PnlBackGroundLayout.setHorizontalGroup(
            PnlBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlBackGroundLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(PnlLogingBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Lbl_Libros_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PnlBackGroundLayout.setVerticalGroup(
            PnlBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlBackGroundLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(PnlLogingBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Lbl_Libros_imagen)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
        String nombre = TxtUsuario.getText();
        String contraseña = new String(Password_1.getPassword());

        if (usuario.validarUsuario(nombre, contraseña)) {
            JOptionPane.showMessageDialog(null, "Bienvenido", "Ingreso exitoso", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            dashboard dash = new dashboard();
            dash.pack();
            dash.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos", "ERROR", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void TxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioActionPerformed

    private void TxtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtUsuarioMouseClicked

    }//GEN-LAST:event_TxtUsuarioMouseClicked

    private void Password_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password_1MouseClicked

    }//GEN-LAST:event_Password_1MouseClicked

    private void BtnIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIngresarMouseEntered
        BtnIngresar.setBackground(Color.green);
    }//GEN-LAST:event_BtnIngresarMouseEntered

    private void BtnIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIngresarMouseExited
        BtnIngresar.setBackground(new Color(0, 153, 0));
    }//GEN-LAST:event_BtnIngresarMouseExited

    private void TxtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtUsuarioMousePressed
        TxtUsuario.setText("");
    }//GEN-LAST:event_TxtUsuarioMousePressed

    private void Password_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password_1MousePressed
        Password_1.setText("");
    }//GEN-LAST:event_Password_1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JLabel LblLogin;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JLabel LblUsuario;
    private javax.swing.JLabel Lbl_Libros_imagen;
    private javax.swing.JPasswordField Password_1;
    private javax.swing.JPanel PnlBackGround;
    private javax.swing.JPanel PnlLogingBackground;
    private javax.swing.JSeparator Separator_password;
    private javax.swing.JSeparator Separator_user;
    private javax.swing.JTextField TxtUsuario;
    // End of variables declaration//GEN-END:variables

//    class FondoPanel extends JPanel{
//        
//        private Image imagen;
//        
//        @Override
//        public void paint(Graphics g)
//        {
//            imagen = new ImageIcon(getClass().getResource("/imagenes/login_background.jpg")).getImage();
//            
//            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
//            setOpaque(false);
//            super.paint(g);
//        }
//    }
}
