package biblioteca;


import biblioteca.Biblioteca;
import biblioteca.libro;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Pagina_principal extends javax.swing.JFrame {

    private biblioteca.Biblioteca biblio;
    DefaultTableModel modelo = new DefaultTableModel();

    public Pagina_principal() {
        initComponents();
        biblio = new Biblioteca();
        modelo = (DefaultTableModel) Tbl_Biblioteca.getModel();
        cargarLibrosEnTabla(biblio);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // Aquí abajo los métodos 
    // Método para cargar libros al JTable
    public void cargarLibrosEnTabla(Biblioteca bibio) {
        // Limpiar el JTable antes de cargar nuevos datos (opcional)

        modelo.setRowCount(0); // Elimina las filas existentes

        // Obtener la lista de libros
        ArrayList<libro> listaLibros = bibio.obtenerLibros();

        // Recorrer la lista de libros y añadirlos al JTable
        for (libro libro : listaLibros) {
            Object[] fila = {
                libro.getName(),
                libro.getAuthor(),
                libro.getYear(),
                libro.getId(),
                libro.getGenre(),
                libro.isBorrowed() ? "Sí" : "No" // Convertir boolean a String
            };
            modelo.addRow(fila); // Agregar la fila al modelo de la tabla
        }

    }

    // Añadir ActionListener al 
    /**    
ComboBoxBorrow.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        
    }
}); **/

// Método para filtrar los datos

// Método para actualizar la tabla



    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PnlFondo = new javax.swing.JPanel();
        Panel_botones = new javax.swing.JPanel();
        Btn_Agregar = new javax.swing.JButton();
        Btn_Eliminar = new javax.swing.JButton();
        Btn_actualizar = new javax.swing.JButton();
        Pnl_titulo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Biblioteca = new javax.swing.JTable();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlFondo.setBackground(new java.awt.Color(255, 255, 255));
        PnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_botones.setBackground(new java.awt.Color(204, 255, 204));

        Btn_Agregar.setBackground(new java.awt.Color(0, 204, 51));
        Btn_Agregar.setText("Agregar datos");
        Btn_Agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_AgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_AgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_AgregarMouseExited(evt);
            }
        });
        Btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AgregarActionPerformed(evt);
            }
        });

        Btn_Eliminar.setBackground(new java.awt.Color(0, 204, 51));
        Btn_Eliminar.setText("Eliminar un libro");
        Btn_Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_EliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_EliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_EliminarMouseExited(evt);
            }
        });
        Btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarActionPerformed(evt);
            }
        });

        Btn_actualizar.setBackground(new java.awt.Color(0, 204, 51));
        Btn_actualizar.setText("Actualizar datos");
        Btn_actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_actualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_actualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_actualizarMouseExited(evt);
            }
        });
        Btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_botonesLayout = new javax.swing.GroupLayout(Panel_botones);
        Panel_botones.setLayout(Panel_botonesLayout);
        Panel_botonesLayout.setHorizontalGroup(
            Panel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_botonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn_Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_actualizar)
                    .addComponent(Btn_Agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        Panel_botonesLayout.setVerticalGroup(
            Panel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_botonesLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(Btn_Agregar)
                .addGap(18, 18, 18)
                .addComponent(Btn_Eliminar)
                .addGap(18, 18, 18)
                .addComponent(Btn_actualizar)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        PnlFondo.add(Panel_botones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 500));

        Pnl_titulo.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Gestión biblioteca");

        javax.swing.GroupLayout Pnl_tituloLayout = new javax.swing.GroupLayout(Pnl_titulo);
        Pnl_titulo.setLayout(Pnl_tituloLayout);
        Pnl_tituloLayout.setHorizontalGroup(
            Pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_tituloLayout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        Pnl_tituloLayout.setVerticalGroup(
            Pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_tituloLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        PnlFondo.add(Pnl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 670, 110));

        Tbl_Biblioteca.setBackground(new java.awt.Color(204, 204, 204));
        Tbl_Biblioteca.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Tbl_Biblioteca.setForeground(new java.awt.Color(51, 51, 51));
        Tbl_Biblioteca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Autor", "Año", "ID", "Genero", "Pestado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tbl_Biblioteca);

        PnlFondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 600, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCargarLibrosMouseClicked(java.awt.event.MouseEvent evt) {
        
        System.out.println("sisi");

    }

    private void Btn_AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_AgregarMouseClicked
        String Nombre = JOptionPane.showInputDialog("Digite el nombre del libro");
        String Autor = JOptionPane.showInputDialog("Digite el autor del libro");
        int anio = Integer.parseInt(JOptionPane.showInputDialog("Digite el año del libro"));

        String Genero = JOptionPane.showInputDialog("Digite el genero del libro");
        int prestadoOption = JOptionPane.showConfirmDialog(null, "¿El libro está prestado?", "Préstamo", JOptionPane.YES_NO_OPTION);
        boolean Prestado = (prestadoOption == JOptionPane.YES_OPTION);

        biblio.AddBooks(Nombre, Autor, anio, Genero, Prestado);
        cargarLibrosEnTabla(biblio);

    }//GEN-LAST:event_Btn_AgregarMouseClicked

    private void Btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_EliminarActionPerformed

    private void Btn_EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_EliminarMouseClicked

        int row = Tbl_Biblioteca.getSelectedRow();

        if (row >= 0) {
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de eliminar este libro?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (confirmacion == JOptionPane.YES_OPTION) {
                modelo.removeRow(row);
                biblio.Borrar_FIla(row);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una fila para eliminar...", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_Btn_EliminarMouseClicked

    private void Btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_actualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_actualizarActionPerformed

    private void Btn_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_actualizarMouseClicked
        
        int row = Tbl_Biblioteca.getSelectedRow();

        if (row >= 0) {

            int seguro = JOptionPane.showConfirmDialog(null, "¿Estás seguro de actualizar este libro?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (seguro == JOptionPane.NO_OPTION) {
                return;
            }

            
            String nombre = JOptionPane.showInputDialog("Digite el nuevo nombre del libro", modelo.getValueAt(row, 0));
            String autor = JOptionPane.showInputDialog("Digite el nuevo autor del libro", modelo.getValueAt(row, 1));
            int anio = Integer.parseInt(JOptionPane.showInputDialog("Digite el nuevo año del libro", modelo.getValueAt(row, 2)));
            String genero = JOptionPane.showInputDialog("Digite el nuevo género del libro", modelo.getValueAt(row, 4));
            int prestadoOption = JOptionPane.showConfirmDialog(null, "¿El libro está prestado?", "Préstamo", JOptionPane.YES_NO_OPTION);
            boolean prestado = (prestadoOption == JOptionPane.YES_OPTION);

            modelo.setValueAt(nombre, row, 0);
            modelo.setValueAt(autor, row, 1);
            modelo.setValueAt(anio, row, 2);
            modelo.setValueAt(genero, row, 4);
            modelo.setValueAt(prestado ? "Sí" : "No", row, 5);

            biblio.actualizarLibro(row, nombre, autor, anio, genero, prestado);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una fila para actualizar...", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        
        
        
        
    }//GEN-LAST:event_Btn_actualizarMouseClicked

    private void Btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_AgregarActionPerformed

    private void Btn_AgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_AgregarMouseEntered
        Btn_Agregar.setBackground(Color.green);
    }//GEN-LAST:event_Btn_AgregarMouseEntered

    private void Btn_AgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_AgregarMouseExited
        Btn_Agregar.setBackground(new Color(0, 153, 0));
    }//GEN-LAST:event_Btn_AgregarMouseExited

    private void Btn_EliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_EliminarMouseEntered
        Btn_Eliminar.setBackground(Color.green);
    }//GEN-LAST:event_Btn_EliminarMouseEntered

    private void Btn_EliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_EliminarMouseExited
        Btn_Eliminar.setBackground(new Color(0, 153, 0));
    }//GEN-LAST:event_Btn_EliminarMouseExited

    private void Btn_actualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_actualizarMouseEntered
        Btn_actualizar.setBackground(Color.green);
    }//GEN-LAST:event_Btn_actualizarMouseEntered

    private void Btn_actualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_actualizarMouseExited
        Btn_actualizar.setBackground(new Color(0, 153, 0));
    }//GEN-LAST:event_Btn_actualizarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagina_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagina_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagina_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagina_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagina_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Agregar;
    private javax.swing.JButton Btn_Eliminar;
    private javax.swing.JButton Btn_actualizar;
    private javax.swing.JPanel Panel_botones;
    private javax.swing.JPanel PnlFondo;
    private javax.swing.JPanel Pnl_titulo;
    private javax.swing.JTable Tbl_Biblioteca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
